versions-url: "https://raw.githubusercontent.com/Bluezly/iconforgrowstock/refs/heads/main/versions.json"

refresh-hours: 6

debug: true

send-pack-on-join: true

fallback:
  enabled: true

default-pack:
  enabled: false
  url: ""
  sha1: ""
  required: false

packs:
  "1.20-1.20.1":
    enabled: false
    url: ""
    sha1: ""
    required: false

  "1.20.2":
    enabled: false
    url: ""
    sha1: ""
    required: false

  "1.20.3-1.20.4":
    enabled: false
    url: ""
    sha1: ""
    required: false

  "1.20.5-1.20.6":
    enabled: false
    url: ""
    sha1: ""
    required: false

  "1.21-1.21.1":
    enabled: false
    url: ""
    sha1: ""
    required: false

  "1.21.2-1.21.3":
    enabled: false
    url: ""
    sha1: ""
    required: false

  "1.21.4":
    enabled: false
    url: ""
    sha1: ""
    required: false

  "1.21.5":
    enabled: false
    url: ""
    sha1: ""
    required: false

  "1.21.6":
    enabled: false
    url: ""
    sha1: ""
    required: false
