name: EachVersionResources
version: 1.0
main: net.bluezly.eachversionresources.Eachversionresources
api-version: "1.20"
description: Sends different resource packs based on the player's Minecraft version.
author: Bluezly

commands:
  pver:
    description: Shows your detected protocol and version.
    usage: /pver [reload|debug]
    permission: eachversionresources.pver

permissions:
  eachversionresources.pver:
    description: Allows use of /pver command.
    default: op
  eachversionresources.reload:
    description: Allows reloading the plugin via /pver reload.
    default: op
